### ISSUE TITLE
fio result structure and meaning

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/ripsaw#101]
A discussion with Alex Calhoun got me thinking about fio-result.json produced by ripsaw fio-bench, specifically the "All clients" section.  Does this section mean anything?  All fio-benchmarks I've used in the past has just given you throughput numbers that were the sum of the individual fio processes (pods in your case) **running at the same time on the same workload**.   But ripsaw is running fio jobs serially  (one at a time) for rw={read,write,randread,randwrite} rather than in parallel.   So how can ripsaw get a valid result by adding up throughputs for jobs running at different times?  I don't think it can.  Also the latency numbers in there are not useful because you can't calculate system-wide percentiles from per-process percentiles.

We could separate out the JSON elements for different workloads (run at different times) and aggregate those results in a meaningful way.  Perhaps it would be easier to just run each fio workload as a separate fio client job, with output files in a separate subdirectory.   As a result, "All clients" now has meaning because all fio pods in fio-result.json were running at the same time on the same workload, so throughput aggregation now makes sense.  The separation of workload results into separate directories would make it easier for anything/anyone else that is analyzing those results.  For example, they could be easily worked on by [ACT](https://github.com/acalhounRH/automated_ceph_test) (Alex's elastic search injector) or a browbench scribe, or whatever equivalent data analysis tool is being used, in parallel with the test run.  Each directory would have the exact parameters and inputs fed to fio, + all the fio logs and JSON that was output by fio as a result.   This is similar to what pbench-fio does in its directory structure also.

Finally, as both [CBT](https://github.com/acalhounRH/cbt/tree/master/benchmark) and [pbench-fio](https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/pbench-fio.md) do, we could add a layer to this directory structure for multiple samples of the same workload (combination of fio parameters) so that %deviation can be calculated from it.   This allows for ripsaw to be extended to run multiple samples of the same data point, which would be vital for demonstrating that results are accurate.   At this point, ripsaw output would become much more similar to CBT and pbench-fio in directory structure and analysis code overlap could be increased.  For example, pbench-fio has a directory structure that indicates workload at top and sample at the next level, such as:

/var/lib/pbench-agent/fio__2019.05.24T14.25.38/1-read-4KiB/sample1/

All this would lead to a natural reuse of existing analysis tools, such as grafana dashboards, with ripsaw.  HTH -ben

**Comment by acalhounRH** [comment]
+1

**Comment by jtaleric** [comment]
> A discussion with Alex Calhoun got me thinking about fio-result.json produced by ripsaw fio-bench, specifically the "All clients" section. Does this section mean anything? 

Isn't this generated by fio itself? I would hope fio would have a sense of the meaning?

> All fio-benchmarks I've used in the past has just given you throughput numbers that were the sum of the individual fio processes (pods in your case) **running at the same time on the same workload**. But ripsaw is running fio jobs serially (one at a time) for rw={read,write,randread,randwrite} rather than in parallel.

@shekharberry wrote the jobfile -- is there a way to change this?

> So how can ripsaw get a valid result by adding up throughputs for jobs running at different times?

If we want to sync them, we can....

> I don't think it can. Also the latency numbers in there are not useful because you can't calculate system-wide percentiles from per-process percentiles.

Correct. We would need to post-processes all the fio result files, right?

> 
> We could separate out the JSON elements for different workloads (run at different times) and aggregate those results in a meaningful way. Perhaps it would be easier to just run each fio workload as a separate fio client job, with output files in a separate subdirectory. As a result, "All clients" now has meaning because all fio pods in fio-result.json were running at the same time on the same workload, so throughput aggregation now makes sense. 

This should be easy to implement. If we want to make sure they all run and don't drift we could use the redis backend between jobs.

>The separation of workload results into separate directories would make it easier for anything/anyone else that is analyzing those results. For example, they could be easily worked on by [ACT](https://github.com/acalhounRH/automated_ceph_test) (Alex's elastic search injector) or a browbench scribe, or whatever equivalent data analysis tool is being used, in parallel with the test run. Each directory would have the exact parameters and inputs fed to fio, + all the fio logs and JSON that was output by fio as a result. This is similar to what pbench-fio does in its directory structure also.

Instead of using a directory, could we index the data necessary for these tools to post-process, and have them pull the data down, to massage the data in the fashion structures it needs to visualise? 

> 
> Finally, as both [CBT](https://github.com/acalhounRH/cbt/tree/master/benchmark) and [pbench-fio](https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/pbench-fio.md) do, we could add a layer to this directory structure for multiple samples of the same workload (combination of fio parameters) so that %deviation can be calculated from it. 

Why couldn't we do this after the fact? Does the current data we have not allow for this?

> This allows for ripsaw to be extended to run multiple samples of the same data point, which would be vital for demonstrating that results are accurate. At this point, ripsaw output would become much more similar to CBT and pbench-fio in directory structure and analysis code overlap could be increased. For example, pbench-fio has a directory structure that indicates workload at top and sample at the next level, such as:
> 
> /var/lib/pbench-agent/fio__2019.05.24T14.25.38/1-read-4KiB/sample1/

Yes - and we don't generate directories, we generate json payloads to index into elastic. Assuming we are not missing any data, Alex's work or pbench could reassemble the structures, right?

> 
> All this would lead to a natural reuse of existing analysis tools, such as grafana dashboards, with ripsaw. HTH -ben

Does fio-distributed avoid this issue?

**Comment by bengland2** [comment]
So after talking to Aakarsh and Joe, I'm of the opinion that all the data that we need is in the existing directory structure in the PV after the test, and it does faithfully represent what fio produces -- it's not in the same format that other tools produce, but is arguably just what fio produces, no more no less.   [Here is a sample](http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/public/openshift/ripsaw/example/) of the test artifacts in the PV produced by the ripsaw fio run.  Unless someone shows that test results are not recoverable from this format, I think we should close this issue.

Specifically we have to:
* ignore "All clients" entry in the fio json (is this a bug in fio? I think so, will take it up with them)
* aggregate just the per-pod entries in the fio json for the same workload type (example: "jobname": "read")
* map job name to job numeric ID (example: write=1,read=2,readwrite=3)
* calculate time windows for each workload (job name) using startdelay and index the log data into Elastic with the right offset time.   
* fio already segregates the log data based on the job (workload) - it's a bit harder because the filename embeds the workload type as a numeric job ID like ./fio_clat.2.log.172.17.0.13, instead of fio_clat.read.log.172.17.0.13, but the information is there.

Aakarsh's elastic search injector does this and his dashboard can therefore show just the completion latency for the "read" workload, or the "write" workload, or any combination of them, since they are just different time intervals for this data.

**Comment by jtaleric** [comment]
Thanks for the clear feedback @bengland2! We appreciate it!
