### ISSUE TITLE
Add creation of minishift/minikube environment for CI

### ISSUE THREAD

**Issue by dry923** [cloud-bulldozer/ripsaw#114]
Per aakarshg I've rolled together a simple setup of the minikube/shift environments for CI. This gets triggered near the start of the test.sh script using blackknight's setup/install playbooks depending on the NODE_LABELS.

Current work is here: https://github.com/dry923/ripsaw/blob/miniinstall/tests/start_mini.sh

A few outstanding questions:
- Should we always install fresh or just see if it is not installed/running?
- Like ^ should we uninstall upon completion?
- If we find a running minishift/kube should we kill it and redeploy, leave it and continue or error?
- Do we need to tweak any of the default cpu/mem/storage from blackknights install defaults.

**Comment by aakarshg** [comment]
> Per aakarshg I've rolled together a simple setup of the minikube/shift environments for CI. This gets triggered near the start of the test.sh script using blackknight's setup/install playbooks depending on the NODE_LABELS.
> 
> Current work is here: https://github.com/dry923/ripsaw/blob/master/tests/start_mini.sh
> 
Nice work
> A few outstanding questions:
> 
> * Should we always install fresh or just see if it is not installed/running?
I think the goal would be to do a fresh install
> * Like ^ should we uninstall upon completion?
So if we're running start_min{shift,kube}.yml it'll automatically delete everything when its kicked off
> * If we find a running minishift/kube should we kill it and redeploy, leave it and continue or error?
This is taken care of by the start_min{shift,kube}.yml, it'll automatically delete everything when its kicked off
> * Do we need to tweak any of the default cpu/mem/storage from blackknights install defaults.
I dont think we'll need to, as we won't run the setup_min{shift,kube}.yml playbook.

Above is my opinion, but another important thing is that re-installing the test environment would add about ~10 minutes to the current run time.

**Comment by dry923** [comment]
> Above is my opinion, but another important thing is that re-installing the test environment would add about ~10 minutes to the current run time.

Regarding the amount of time. About how long/often does this need to be triggered by hand? Time saved might be > than the extra 10 minutes.

**Comment by aakarshg** [comment]
- [ ] Iterate through all test scenarios even if one fails, and then display a summary
- [ ] Before the start of the run, do a delete on the deploy dir as well as the crs and ignore failures
- [ ] add another additional trigger to a job, that'd redeploy the platform for testing before running tests

**Comment by aakarshg** [comment]
we can close this out officially as the CI environments are now stable ( minishift was the only PITA candidate )
