### ISSUE TITLE
Pgbench CR hard coding thread count = 1

### ISSUE THREAD

**Issue by netzzer** [cloud-bulldozer/ripsaw#115]
The value of threads: in CR is not being used. Below is how CR is configured and below is output after CR is deployed.

**Comment by netzzer** [comment]
The value of `threads:` in CR is not being used. Below is how CR is configured and below is output after CR is deployed.
$ cat ripsaw_v1alpha1_pgbench_cr.yaml 
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: pgbench-benchmark
  namespace: ripsaw
spec:
  workload:
    name: "pgbench"
    args:
      clients: 3
      **threads: 100**
      scaling_factor: 1

$ oc logs pgbench-benchmark-pgbench-client-1-784b9
Init Database 1
creating tables...
10000 tuples done.
20000 tuples done.
30000 tuples done.
40000 tuples done.
50000 tuples done.
60000 tuples done.
70000 tuples done.
80000 tuples done.
90000 tuples done.
100000 tuples done.
set primary key...
vacuum...done.
Running PGBench 1
Scale option ignored, using pgbench_branches table count = 1
starting vacuum...end.
transaction type: TPC-B (sort of)
scaling factor: 1
query mode: simple
number of clients: 3
**number of threads: 1**
number of transactions per client: 10
number of transactions actually processed: 30/30
tps = 448.296473 (including connections establishing)
tps = 491.843594 (excluding connections establishing)

**Comment by dustinblack** [comment]
This is against my development branch. I'll take care of it.

**Comment by dustinblack** [comment]
The threads value seems to be used correctly in the ansible task:

```
      - name: benchmark
        image: "quay.io/cloud-bulldozer/pgbench:latest"
        command: ["/bin/sh", "-c"]
        args:
          - "export PGPASSWORD='{{ item.1.password }}';
             export pgbench_auth='-h {{ item.1.host }} -p {{ item.1.port }} -U {{ item.1.user }}';
             echo 'Init Database {{ item.0|int + 1 }}';
             pgbench $pgbench_auth -i -s {{ pgbench.scaling_factor }} {{pgbench.init_cmd_flags }} {{ item.1.db_name }};
             if [ $? -eq 0 ]; then
               echo 'Running PGBench {{ item.0|int + 1 }}';
               pgbench $pgbench_auth -c {{ pgbench.clients }} -j {{ pgbench.threads }} -s {{ pgbench.scaling_factor }} {{ pgbench.cmd_flags }} {{ item.1.db_name }};
             fi"
```

**Comment by dustinblack** [comment]
This seems to be just a pgbench syntax problem. The `clients` value must be a multiple of the `threads` value, not the other way around. I'm guessing log output provided here was from a previous run, not the one with this CR, since this should have resulted in a pgbench syntax error and a failed run.

Added a note to the example CR file in my dev branch.
