### ISSUE TITLE
fio-d: Allow running FIO on predefined PVC and pod

### ISSUE THREAD

**Issue by RazTamir** [cloud-bulldozer/ripsaw#119]
I would like to run FIO-cr over a predefined PVC attached to an existing pod.
This is mainly needed as testing efforts not specific to benchmark

**Comment by vasukulkarni** [comment]
@dustinblack can you take this up as high priority? I am planning to intergrate ripsaw with ocs-ci. Thanks!

**Comment by jtaleric** [comment]
@vasukulkarni you want to pass a PVC to the CR to run FIO against? That should be a simple change to fio.

**Comment by vasukulkarni** [comment]
@jtaleric I will create a PVC and would like to use that name either for FIO or any workloads that ripsaw runs, In same example files, I think I saw we can specify pvc name, but maybe you can clarify how to use it?

**Comment by dustinblack** [comment]
> @jtaleric I will create a PVC and would like to use that name either for FIO or any workloads that ripsaw runs, In same example files, I think I saw we can specify pvc name, but maybe you can clarify how to use it?

The current implementation will always create the PVC based on the information provided in the CR. Using an existing PVC is *probably* a relatively simply logic change.

Do you need the fio role specifically, versus the fio-d role? I think the main reason you might need that is if you are going to use the `get_url` functionality to provide a custom jobfile. I ask because I'm hoping to focus on fio-d right now and eventually merge the two into one role.

**Comment by vasukulkarni** [comment]
> > @jtaleric I will create a PVC and would like to use that name either for FIO or any workloads that ripsaw runs, In same example files, I think I saw we can specify pvc name, but maybe you can clarify how to use it?
> 
> The current implementation will always create the PVC based on the information provided in the CR. Using an existing PVC is _probably_ a relatively simply logic change.
> 
> Do you need the fio role specifically, versus the fio-d role? I think the main reason you might need that is if you are going to use the `get_url` functionality to provide a custom jobfile. I ask because I'm hoping to focus on fio-d right now and eventually merge the two into one role.

The issue was created for fio specifically, but In general, we want to utilize the ripsaw framework for any workload (fio, couchbase, mongo etc) with pvc(varying size and backend) created in our ci, I dont think it matters much what pod we use.

**Comment by chawlanikhil24** [comment]
I think its pretty simple to run pods with your own attached PVCs. Just need to skip some tasks in the FIO role, and in the pod definition, and in the end, need to mount the pre-defined PVC to PODs, but I've a concern , why do you not want to opt for creating PVC using storageClasses ? I mean what would be the difference b/w user-defined PVC and ripsaw created PVC using storageClass ?

Another thing is, If we are creating 100 pods for tests, then we create 100 PVCs and attach them to the respective pod, but in case of user-defined PVC, will anyone be using 100 PODS or just stick to the count of 1 ? 
If you going to create 100 PVCs manually, then all the PVCs has to be supplied in a list in CR file ? 
But then 100 PVCs creating manually ? 

@RazTamir @vasukulkarni @jtaleric @dustinblack
