### ISSUE TITLE
RFE: Allow full flexibility to run fio jobs

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#12]
With the fio jobfile templated in roles/fio-bench/templates/job.fio.j2, we either have to restrict fio parameters to a subset that we are prepared to support, or we have to template out every possible fio parameter.

In order to support full flexibility of fio jobs, it might make more sense to pull the job file out as something that is user-provided as part of the CR or an include of the CR. Off hand, it seems like there would still need to be an amount of templating, so I'm not immediately sure how to import a raw standard-formatted fio jobfile.

Another option proposed is to split fio into two different types/roles -- One would be a basic "fio-simple-bench" in which the jobfile would remain templated in the role with limited parameters provided to the user to adjust in the CR. The second would be a "fio-user-bench" in which the fio jobfile would be provided as part of the CR outside of the role.

**Comment by jtaleric** [comment]
This has been implemented!
