### ISSUE TITLE
Add figlet to CI systems

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#126]
Just a simple hack to help with CI log output readability. I've added to each test script:

`figlet $(basename $0)`

Which will output something like this at the beginning of each script:
```
 _            _       _                         _       _     
| |_ ___  ___| |_    | |__  _   _  _____      _| |  ___| |__  
| __/ _ \/ __| __|   | '_ \| | | |/ _ \ \ /\ / / | / __| '_ \ 
| ||  __/\__ \ |_    | |_) | |_| | (_) \ V  V /| |_\__ \ | | |
 \__\___||___/\__|___|_.__/ \__, |\___/ \_/\_/ |_(_)___/_| |_|
                |_____|     |___/
```

But these commands are disabled right now because figlet is not available on the CI systems.

**Comment by dry923** [comment]
Merged in https://github.com/cloud-bulldozer/ripsaw/pull/167
