### ISSUE TITLE
fio-d: roles should include commands to drop caches

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#130]
fio best practice is (generally) to sync and drop caches with every iteration/sample. This is usually done with:

```
sync; echo 3 > /proc/sys/vm/drop_caches
```

We could add this as a bash command to each test sequence, or we could include it directly in the fio job file with:

```
exec_prerun=sync; echo 3 > /proc/sys/vm/drop_caches
```

Might be worthwhile to make this optional in the CR for the off chance someone wants to test without this.

**Comment by aakarshg** [comment]
after the conversation earlier about pr #213 , this looks like outside scope of ripsaw, and more specific to snafu so closing this out.
