### ISSUE TITLE
fio-d: Implement servers as a list to loop through

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#140]
Pushing fio to find system limits usually involves ramping up the parallelism of worker jobs. You can do this via threads per worker (which should also be implemented as a list; separate issue), but it is often valuable, particularly for a distributed storage SUT, to increase the total number of workers in order to get past any per-worker bottlenecks and properly saturate the storage system.

Implementing the `servers` key in the CR as a list would allow us to iterate through server counts as an outer loop to `samples`. This is a bit complicated with the current implementation of the fio-d role as we first run an ansible task to spin up the number of workers as fio server pods before executing the fio job task. So we would need to be able to spin up servers, run a job, increment the number of servers, and then run the subsequent job from the `server` list.

One option is to use the highest value from the `servers` list and spin up a number of server pods once equal to that maximum value, that way only the fio job task needs to be looped. The downside is that the server pods unused for the lower-value jobs will still be consuming resources in the k8s system and could potentially skew the results.

Another option may be to implement this loop at the `playbook.yaml` level, similar to the original proposed method for implementing the `samples` feature.

**Comment by aakarshg** [comment]
> One option is to use the highest value from the `servers` list and spin up a number of server pods once equal to that maximum value, that way only the fio job task needs to be looped. The downside is that the server pods unused for the lower-value jobs will still be consuming resources in the k8s system and could potentially skew the results.
> 

@bengland2 @jtaleric @dustinblack what do you think about the above mentioned methodology?

**Comment by dustinblack** [comment]
> > One option is to use the highest value from the `servers` list and spin up a number of server pods once equal to that maximum value, that way only the fio job task needs to be looped. The downside is that the server pods unused for the lower-value jobs will still be consuming resources in the k8s system and could potentially skew the results.
> 
> @bengland2 @jtaleric @dustinblack what do you think about the above mentioned methodology?

I'm generally comfortable with this, but have only a minor concern when it may mean that hundreds or thousands of server pods are pre-spun, waiting for workloads initiated from the clients. If we think of these as just idle processes and ports, it doesn't seem like a major concern. But we could possibly get into impacts at the k8s api level or the large number of pre-created PVs that could skew the results.

**Comment by bengland2** [comment]
@dustinblack I don't see a problem in principle with starting up the servers, once.    fio servers don't generally consume significant resources unless a job is running.   But are we over-thinking it?   Let's just get it to run at all, then see whether this really helps elapsed time of the test.    In real world, you have to run fio jobs for long enough that the system reaches equilibrium and can't cache the dataset, so I doubt this is going to determine test's elapsed time.
