### ISSUE TITLE
fio-d: List of small issues/enhancements

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#141]
- [x] **PVCs should have unique names between runs.** Currently these are `claim-{{ item }}`, which can at the very least cause some annoyances if deleting and then re-applying the CR, as the operator will trigger creating of a PVC with the same name as one that is still being deleted.

- [x] **Implement size- vs. time-based runs.** Currently the CR and templates allow for a time-based run in the jobfile only. A nice-to-have feature would be an option to run based on file size.
  - PR #205 -- Decision was to implement all writes a size-based and all reads as time-based.

- [x] **Workers/threads should be a list to loop through.**
  - PR #147

- [x] **File size should be a list to loop through.**
  - Cancelling as it's probably not important anymore

- [x] **Merge jobfile templates into one.** I don't see a good reason to have multiple templates. We should simply be adjusting values in the templates based on the type of job and the specific parameters provided in the CR.
  - PR #154

- [x] **Provide jobname in a better way.** Seems like a weird thing to name explicitly as a value in the CR. Maybe `jobname` can just match `job` in the CR.
  - PR #147 

- [x] **Merge fio and fio-d into one role.**
  - PR #142

- [x] **Implement some way of balancing server pods across nodes.**
  - PR #209

- [ ] **Need to consider how a RWX PV would be tested.**

- [x] **Git rid of redundant pin boolean.** Simply providing a pin host or not should be sufficient. Also... Does pinning even make sense in a distributed test? The way this is implemented means all server pods would go to the single pin host.
  - PR #160

- [x] **The `filesize` in the CR should be passed with the scale, just as the fio command would accept it (i.e., 2g instead of 2)**
  - PR #200

- [x] **The `jobname` in the CR is redundant to the `job` and can be removed**
  - PR #147

**Comment by dustinblack** [comment]
> * **PVCs should have unique names between runs.** Currently these are `claim-{{ item }}`, which can at the very least cause some annoyances if deleting and then re-applying the CR, as the operator will trigger creating of a PVC with the same name as one that is still being deleted.

I played with implementing this, but it introduces another problem of non-idempotence when ripsaw loops the role, causing new PVCs to be created each time.

**Comment by aakarshg** [comment]
> I played with implementing this, but it introduces another problem of non-idempotence when ripsaw loops the role, causing new PVCs to be created each time.

Looks like #105 needs to be prioritized, as it'll help address the problem that you've mentioned.

**Comment by dustinblack** [comment]
> * **Workers/threads should be a list to loop through.**

Addressed in PR #147

**Comment by dustinblack** [comment]
> * **Merge jobfile templates into one.** I don't see a good reason to have multiple templates. We should simply be adjusting values in the templates based on the type of job and the specific parameters provided in the CR.

Partially addressed in PR #147. The the jobfile templates have been heavily cleaned up, which should lead to an easier job merging them.

**Comment by dustinblack** [comment]
> * **Provide jobname in a better way.** Seems like a weird thing to name explicitly as a value in the CR. Maybe `jobname` can just match `job` in the CR.

The jobname key was removed with PR #147

**Comment by aakarshg** [comment]
@dustinblack do we have still have to check off any of the mentioned improvements ?

**Comment by dustinblack** [comment]
Updated the list in the OP, and everything has been resolved except "Need to consider how a RWX PV would be tested."

I think if you provided an RWX volume right now, things would break. It's worth a test and a discussion about whether this is a feature we need.
