### ISSUE TITLE
Discussion: pin_server vs pin_node or other key name in CR

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#159]
We currently use the key `pin_server` across a few roles to identify the k8s node to which a pod or pods will be pinned with a `nodeSelector` in the template. I think the name of this key is a little confusing -- Since the value you pass to `pin_server` is a k8s node name to which you are pinning, on the surface I would argue that it should be called `pin_node` instead (which is what I used in the pgebench role).

However, in the uperf and iperf roles, there is also a `pin_client` key, so it is more clear that the key name is in the context of what you are pinning, not where you are pinning it.

The keys might be more clear in all conditions as something like `pin_server_to_node` and `pin_client_to_node`, but perhaps I'm overthinking it and we should just address this in documentation. To me, it is valuable to make the usage of the CR structure as self-explanatory as possible in order to enhance usability, which will better drive adoption and limit the pings we get to answer howto questions.

**Comment by aakarshg** [comment]
@dustinblack any further progress on this ? I think we can close this out because it's not an issue per se. @jtaleric @dry923 thoughts?

**Comment by dustinblack** [comment]
This is just a point on consistency across CRs, which IMO is important to reduce user confusion. Nothing's broken, clearly, but it's still an issue that maybe an intern could pick up.
