### ISSUE TITLE
RFE: CI environments to use local registries

### ISSUE THREAD

**Issue by aakarshg** [cloud-bulldozer/ripsaw#179]
We've been seeing exceptionally longer pull times to download images from Quay.io, so it'll be optimal if we could use a local registry. [Blog post](https://tortuemat.gitlab.io/blog/2018/03/18/kubernetes-with-local-registry/) shares more details on how it can be done. 

By using a local registry, we'll be eradicating the issue around quay pulltimes and also the need for the insanely long timeouts on wait conditions in ci scripts

**Comment by bengland2** [comment]
not only that but as we move to larger-scale openshift clusters (e.g. in public cloud), we don't multiply quay traffic by N, when we could just download it once to local cluster.    Wish we could load the image once into a ceph pool where it is accessible to everyone locally and directly and may even be cached in RAM, sort of like OpenStack glance.

Are you seeing flakiness *uploading* to quay.io?   I have recently, where it would try to push, fail saying it was busy, then try the whole layer again.  It's annoying.

**Comment by aakarshg** [comment]
I think we can close this out, given that we haven't seen any issues so far with quay pull times?? @dustinblack @jtaleric @bengland2 @dry923 thoughts on this?

**Comment by bengland2** [comment]
@aakarshg not a problem lately.

**Comment by aakarshg** [comment]
alright @bengland2 closing this out to clear the clutter, can reopen later if needed. thanks
