### ISSUE TITLE
RFE: Enhance uperf workload to work between ServiceIPs

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/ripsaw#24]
Since we have the pod to pod tests in place, it would be good to have a way to do serviceIP to serviceIP tests also.

**Comment by jtaleric** [comment]
Hey @smalleni can you elaborate on this?

**Comment by smalleni** [comment]
Sure @jtaleric Something like https://github.com/openshift/svt/blob/master/networking/synthetic/svc-ip-test-setup.yaml where the test is run in between serviceIPs instead of directly pods. The services are backed by pods.

**Comment by jtaleric** [comment]
@smalleni I am trying to understand what this Ansible playbook is doing with regard to ServiceIPs. 

If you are asking if we can _pin_ specific sender / receivers like they are doing here[1], I am totally fine with that sort of addition. This ties into an RFE I have to jinja template the creation of or Pods/Jobs/VMs. 

[1] https://github.com/openshift/svt/blob/master/networking/synthetic/svc-ip-test-setup.yaml#L58-L64

**Comment by smalleni** [comment]
So, the playbook creates pods and a service to expose those pods. The test is run in between serviceIPs and not podIPs. Currently you have tests to run in between pod IPs. Service to Service throughput is also an important metric especially because applications only consume services.

**Comment by jtaleric** [comment]
Hey @smalleni I am going to work on this soon... However, I am still not 100% on ServiceIP. Host networking should obtainable, same with scheduling pods across nodes... I will tag my PR to suggest it fixes this issue, hopefully you can put your .02 on it.

**Comment by smalleni** [comment]
@jtaleric Thanks for looking into this. So, to reiterate the idea, launch a bunch of pods, label them as senders and front end them with a service. Same thing with receiver pods. Now, run pbench-uperf using the sender and receiver IPs as serviceIPs instead of pod IPs.
