### ISSUE TITLE
RFE: Make sure that crs are backwards compatible across a version

### ISSUE THREAD

**Issue by aakarshg** [cloud-bulldozer/ripsaw#245]
Currently crs are not backwards compatible at all, meaning that a cr that works with master branch today isn't guaranteed to work tomorrow ( if the master branch of ripsaw changes say with #218 getting merged uperf cr's need a new key in the cr ). 

Given that master is fast moving, it probably is okay. However, this would also mean that the cr that worked with 0.0.1 branch of ripsaw isn't gonna work either with the master release of ripsaw. So we should look at establishing what backward compatibility are we willing to support with crs, and following are the choices:

1. CRs should always be backwards compatible meaning a cr working now should also work the same way in future with no changes required whatsoever.
2. CRs to be backwards compatible with minor releases so cr working with 0.0.1 version should definitely work with 0.0.2 or 0.0.9 version of ripsaw but it's okay if it doesn't work with 0.1.0 version of ripsaw. 
3. CRs don't have to be backwards compatible at all meaning that a cr working with 0.0.1 version will not be expected to work against 0.0.2 version. 

Open for discussion and votes to figure out the best way to move forward

**Comment by aakarshg** [comment]
@bengland2 @jtaleric @jeniferh @dry923 @dustinblack @chaitanyaenr thoughts on this?

**Comment by bengland2** [comment]
I don't think this is a valid RFE.  It's impossible to guarantee in benchmark-independent parts of  ripsaw that CRs are backwards compatible - that depends on the benchmark implementation, where the CRs are interpreted.   It should be *possible* to implement backwards compatibility for CRs in a ripsaw benchmark, but I think it already is.

**Comment by jtaleric** [comment]
My suggestion is simple but might be complex. 

The initial definition of a workload CR (once deemed Stable) should always be backwards compatible if new `key:value`'s are introduced. 

For example, UPerf has been pretty stable, however we introduced a new key, `kind`. For everyone who was using UPerf, that attempted to run their previous generation CR. The result was failure. Simple due to this new missing key `kind`. They were not making changes to their previous CR, they simply updated to the latest Ripsaw, and their old CR is now invalid. This isn't totally obvious to them.

My argument is we need to *default* values that are newly introduced vs have the user explicitly have to add new keys, which they have no intention on possibly using. 

What if they maintain their own set of Ripsaw CRs, instead of using the *maintained* ones we have?

**Comment by bengland2** [comment]
Yes, if you add new keys to your CR yaml, you can always define a default value for the new keys, and old CRs can take advantage of these default values to execute without change.   That's up to the benchmark implementer.  The example CR provided in github for the benchmark could include comments defining what the default values are.

**Comment by aakarshg** [comment]
Making sure that CRs are always backwards compatible would mean testing all the possible variations of a cr against each version of ripsaw ( because like Joe said what if the user maintains their own cr ? ) and ensuring the output is similar. This not only adds complexity while writing code especially adding new features but also has the additional testing overhead mentioned above during releases. However maintaining backwards compatibility across minor versions would provide us only a limited set of versions of ripsaw to test the cr against. 

Another important thing to note here is this that when using operatorhub for installs, we can replace an older version with a newer version on the fly. This would mean that an user running lets say 0.0.1 version prior would expect all the same features with 1.0.0 version as well, despite there being a significant major release difference and functionality may have changed. 

I'd prefer not having to contributors bind to making sure crs are always backwards compatible ( we don't know what new future we'd like to implement which would mean re establishing the stable definition of a workload cr ), but do agree that it makes sense to maintain a bit of backwards compatibility so users don't have to constantly update their CRs so i'm leaning towards maintaining backwards compatibility across minor versions so a cr working with ripsaw's version 0.0.1 should work with 0.0.9 but doesn't have to work with 0.1.0. This would also take additional overhead off me of having to do so much testing between releases.
