### ISSUE TITLE
RFE [FIO] Test clock=gettimeofday for getting absolute timestamps

### ISSUE THREAD

**Issue by aakarshg** [cloud-bulldozer/ripsaw#257]
Test if using clock=gettimeofday will help with getting absolute timestamps.

**Comment by aakarshg** [comment]
@bengland2 and @acalhounRH have you tried this and was wondering if there's any potential gotchas or impact to the testing process  if we used clock=gettimeofday

**Comment by bengland2** [comment]
@aakarshg  https://fio.readthedocs.io/en/latest/fio_doc.html see clocksource parameter and the tradeoffs written about there.   Inside VMs, gettimeofday() can be very expensive (has to go through to the hypervisor) and can even result in massive clock skew in VMs if there are enough of them.
