### ISSUE TITLE
CI minikube version too old

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/ripsaw#272]
@dry923  could you comment on this?  On aramis CI host, the minikube version is too old, I think.  A[ more current version of minikube is 1.6.2](https://github.com/kubernetes/minikube/releases) .  What version should we be using?

the aramis host was the CI node referenced in the jenkins job log for minikube_jjb CI test environment.

$ ssh root@perf-sm5039-4-8.perf.lab.eng.rdu2.redhat.com
root@perf-sm5039-4-8.perf.lab.eng.rdu2.redhat.com's password: 
X11 forwarding request failed on channel 0
Last login: Tue Jan 14 17:28:50 2020 from 10.10.120.93

[root@perf-sm5039-4-8 ~]# ssh aramis
Last login: Tue Jan 14 17:39:14 2020 from 10.1.184.194

[root@aramis ~]# minikube version
minikube version: v0.35.0

[root@aramis ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bengland2** [comment]
@dry923 OCP 4.3 uses kube 1.16, *way* ahead of where CI is above.

**Comment by bengland2** [comment]
[minikube 1.5.2](https://github.com/kubernetes/minikube/releases/tag/v1.5.2) has K8S 1.16.2, which should be compatible with OCP 4.3, so this seems like a good place for the CI to be running, right?

**Comment by dry923** [comment]
@bengland2 agreed. I'll look to get it updated. on the various ci boxes.

**Comment by dry923** [comment]
@bengland2 updated Snafu and Stockpile CI. Will look to get Ripsaw done in the next day or so

**Comment by dry923** [comment]
```
[root@porthos blackknight]# minikube version
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty
[root@porthos blackknight]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aakarshg** [comment]
Can this be closed @dry923

**Comment by dry923** [comment]
Minikube updated in Ripsaw CI now as well. Closing.
