### ISSUE TITLE
RFE Add optional fill job to fio workloads

### ISSUE THREAD

**Issue by acalhounRH** [cloud-bulldozer/ripsaw#301]
When testing OCS it is ideal that the cluster is at 50% of its capacity to get stable/consistent results, due to the way ripsaw is currently implemented users do not have the ability to do this. 

Ideally If the option is enabled, an extra write job would be included that would precede the user specified test and would not include runtime allowing it to fill the cluster before the user job files.

Currently I have been filling the cluster on the initial executing of fio CR and running my test in pod debug mode, although because the debug is torn down after some time by OCP testing doesn't complete. 

Request that this be a high priority item as it blocks OCS RBD testing 

@aakarshg @jtaleric @bengland2 @dustinblack

**Comment by bengland2** [comment]
@acalhounRH  s/proceed/precede/.  I think you should require that the RBD volumes be pre-written to get stable, consistent results.   I don't think you should always require the cluster to be at 50% of capacity - this can take a REALLY LONG TIME.   And you can get stable, consistent results without 50% of capacity being used.      That's a separate issue - at some point we should measure performance vs space consumption, which you can do by increasing the volume size, but it's not practical to fill up the storage on every run.   As long as the RBD volumes that are initialized in this way are the same ones that the fio tests run on, this should work.   The volume initialization stage can use 4-MB I/O size with O_DIRECT to speed things up.

**Comment by acalhounRH** [comment]
ACK

Filling up the cluster to a specific percentage is/should be based on users setting the volume size and number of servers. that being said I agree that we should hard code the fill to 4MB and O_DIRECT=1. 

suggested job file would be:

[global]
    directory={{fio_path}}
    filename_format=f.\$jobnum.\$filenum
    clocksource=clock_gettime
    kb_base=1000
    unit_base='8'
    ioengine=libaio
    size={{fiod.filesize}}
    bs=4096
    iodepth={{fiod.iodepth}}
    direct=1
    numjobs={{numjobs}}
    rw=write

**Comment by bengland2** [comment]
I've been testing with prefill: true and it's the only way to go for a large test, otherwise you get fio doing writes to the entire drive 4-KiB at a time with O_DIRECT, which is horribly slow.    No other way for OCS testing.  I'm about to submit a PR to change fio CRs to expect prefill: true , so sequential writes can be done time-based rather than for entire volume, and even if samples: 3 is used you don't have to fill the device 3 times.

**Comment by acalhounRH** [comment]
The prefill job is not tied into samples, I believe we just need to update the example fio CR such that prefill: true

**Comment by acalhounRH** [comment]
@aakarshg are we okay with closing this issue?

**Comment by aakarshg** [comment]
closed through #302
