### ISSUE TITLE
Discussion: Creation/handling of additional resources required 

### ISSUE THREAD

**Issue by aakarshg** [cloud-bulldozer/ripsaw#31]
There can be cases where the infra/workloads would require to create additional resources which could be something like RBAC and since it's not required for the operator itself, It wouldn't make sense to mandate user to create them. So thus there are 2 ways to approach this problem:
-  Request user to create the necessary resources after deploying operator and before applying the cr. This would put the burden of managing the resources lifecycle on the user, and thus would not require the operator to do anything more. The issue with this is relying on user to make the appropriate changes and also that it'll require more user involvement.
- Have operator create the resources on the go i.e. if user applies a cr that requires a workload/infra to have additional resources such as RBAC it'll create on the fly. The issue with this is that it requires the operator to delete these RBAC based on conditions( requiring significantly more logic). But if the user somehow manages to delete the operator, then that'd be futile. 

What do you think is the best way to move forward?

**Comment by jtaleric** [comment]
We have decided to not have Ripsaw manage this.

**Comment by aakarshg** [comment]
Closing this as it's been decided to not have Ripsaw manage the resources required by other operators.
