### ISSUE TITLE
Connecting to a Elasticsearch with TLS self-signed certificates do not work

### ISSUE THREAD

**Issue by ddomingu** [cloud-bulldozer/ripsaw#312]
Hi,

Currently ripsaw is not capable to connect to an Elasticsearch server deployed using TLS self-signed certificates.

2020-04-15T12:29:18Z - WARNING  - MainProcess - run_snafu: Elasticsearch connection caused an exception :Root certificates are missing for certificate validation. Either pass them in using the ca_certs parameter or install certifi to use it automatically.

Regards.

**Comment by bengland2** [comment]
good point.   Someone should go to letsencrypt.org and get one.

**Comment by aakarshg** [comment]
Hi @ddomingu thanks for pointing this out, that's right today ripsaw isn't capable of using TLS self-signed certificates. 

Ripsaw invokes benchmark specific wrapper in [snafu](https://github.com/cloud-bulldozer/snafu/) for parsing benchmark output and indexing data to elasticsearch. Given that, ca_certs will expect the certificate path to be present, there'll be changes needed to ripsaw to attach another configmap based on a parameter set in the cr, and accordingly have snafu wrapper use that certificate in path for connection to es. 

Currently we don't have a lot of bandwidth to get this done, but we can definitely try to help with this if you'd like to pick it up,

**Comment by aakarshg** [comment]
@ddomingu can you PTAL at @rsevilla87's PR - https://github.com/cloud-bulldozer/snafu/pull/169 and see if this will be okay for you to skip tls cert verification ? That'll be an easy workaround, however the pr wont be useful at all, if you'd actually prefer verifying with the certs.

**Comment by ddomingu** [comment]
@aakarshg yes with that is more than enough thanks! Verifying certs would be far more complex as the certificate CA should be shared attaching a new configmap to ripsaw. With this PR my issue is fixed, thanks! @rsevilla87++
