### ISSUE TITLE
smallfile benchmark still requires es_index in CR

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/ripsaw#324]
in resources/crds/ripsaw_v1alpha1_smallfile_cr.yaml there is no es_index field and the CR fails, but if you include es_index: ripsaw-smallfile as done in the tests/test_crs/valid_smallfile.yaml, the CR works.   This field should not be necessary, have to fix in snafu/smallfile_wrapper/

**Comment by dry923** [comment]
@bengland2 this looks to have been resolved based on my testing

The es_index variable has a default set
```
          - name: es_index
            value: "{{ elasticsearch.index_name | default("ripsaw-smallfile") }}"
```

We should remove the redundant line from the test cr but it does not hurt anything. Can you confirm this is good?

**Comment by jtaleric** [comment]
@bengland2 ?

**Comment by bengland2** [comment]
Will clean this up later.
