### ISSUE TITLE
[FIO]: Elasticsearch index 'ripsaw-fio-analyzed-result' doesn't record the std-deviation for randomread and randomwrite

### ISSUE THREAD

**Issue by keesturam** [cloud-bulldozer/ripsaw#344]

**Comment by aakarshg** [comment]
Hi @keesturam, can you please open the issue on https://github.com/cloud-bulldozer/snafu/ ? Because that's where the fix will have to land. Thanks

**Comment by aakarshg** [comment]
closed in favor of https://github.com/cloud-bulldozer/snafu/issues/180
