### ISSUE TITLE
Update fio to a newer version.

### ISSUE THREAD

**Issue by mykaul** [cloud-bulldozer/ripsaw#358]
It's not clear to me where the fio binary is coming from, but it's 1.5 years/old (3.12).
Looking at https://quay.io/repository/cloud-bulldozer/fio/manifest/sha256:4f1fa8a2fc9d39ea843af6e5fed4f77e41af116df92acd8fcc64bb96d2e4f74e?tab=layers it seems it's just a binary copied over?

**Comment by rsevilla87** [comment]
Hey @mykaul , we compile and copy the binary when we build the container. Find the code here
https://github.com/cloud-bulldozer/snafu/blob/master/fio_wrapper/Dockerfile#L4-L5

I'd say that you are using a wrong image tag for fio because the latest one is built with fio-3.19
```
$ podman run --rm  quay.io/cloud-bulldozer/fio:latest fio --version
fio-3.19
```

**Comment by mykaul** [comment]
ACK - I mixed up different containers - the one I've looked at was installing an fio. This one is good.

**Comment by mykaul** [comment]
(Now that I look at the Dockerfile - unsure why we compile fio and not just install it from RPM...)

**Comment by rsevilla87** [comment]
Hey @mykaul, Fio is not present at ubi8 official repositories. In the other hand, container building is performed by quay and CI, and CI doesn't use layer caching.

Anyway, feel free so submit some PR to optimize Dockerfiles. Thanks!
