### ISSUE TITLE
fio fails with Invalid Argument due to invalid buflen for O_DIRECT

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/ripsaw#386]
I'm seeing this error from fio client log.

```
2020-08-12T00:57:58Z - ERROR    - MainProcess - trigger_fio: Fio failed to execute
2020-08-12T00:57:58Z - ERROR    - MainProcess - trigger_fio: Output file: <fio-server-1-benchmark-d1c12d98-wpnkq> fio: output file open error: No such file or directory
<fio-server-1-benchmark-d1c12d98-wpnkq> fio: io_u error on file /tmp/172.18.0.8.f.\0.\0: Invalid argument: read offset=241252000, buflen=4000
<fio-server-1-benchmark-d1c12d98-wpnkq> fio: pid=15, err=22/file:io_u.c:1787, func=io_u error, error=Invalid argument
client <172.18.0.8>: exited with error 1
```

It is caused by using O_DIRECT with a buflen of 4000, a no-no (must be power of 2, I think 4096 or more).   The root cause appears to be kb_base=1000 in the jobfile.   When I force kb_base=1024 then it's happy again.

**Comment by rsevilla87** [comment]
What block size size you use?. @mulbc had a similar issue that fixed with was fixed with https://github.com/cloud-bulldozer/ripsaw/pull/376

**Comment by mulbc** [comment]
Indeed! Check out this section of the Readme:
https://github.com/cloud-bulldozer/ripsaw/blob/master/docs/fio_distributed.md#understanding-the-cr-options

And set your blocksize to `4KiB` instead of `4k` and everything should work

**Comment by bengland2** [comment]
ok, never mind, was just an old CR that was throwing things off.
