### ISSUE TITLE
RFE: Allow CI to test against multiple versions of various environments - k8s, okd, ocp 

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#46]

**Comment by aakarshg** [comment]
This issue requires the last sub task mentioned in [the issue](https://github.com/cloud-bulldozer/ripsaw/issues/114#issuecomment-507401316) #114

**Comment by aakarshg** [comment]
This can be officially closed given that our CI runs against upstream k8s and okd ( as well as platform of minkube vs kni )
