### ISSUE TITLE
rfe: logo for ripsaw

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/ripsaw#53]
Need a sweet new logo for Ripsaw!

**Comment by maryshak1996** [comment]
hey @jtaleric ! I'm happy to help out here. could you just include some context to help me understand what 'Ripsaw' is, from an outsider's perspective? A few things that would help the design process here:

- Are there any visuals that come to mind that I could use as inspiration?
- What kinds of words would you use to describe Ripsaw that you would want to convey the spirit of in this logo (ie. innovative, cutting edge, fast, reliable, customizable, etc.)?
- What types of places do you plan for this logo to be most prominent (Web, digital products/consoles, physical swag, printed materials, etc.)

Looking forward to helping you out with this :)

**Comment by jtaleric** [comment]
hey @maryshak1996 !!
> hey @jtaleric ! I'm happy to help out here. could you just include some context to help me understand what 'Ripsaw' is, from an outsider's perspective? A few things that would help the design process here:
> 
> * Are there any visuals that come to mind that I could use as inspiration?

So, when thinking about the `benchmark operator` - I tend to think something that will run workloads in an automated fashion. When I was digging around online, I found [1]. Which led to the name, due to the autonomous capabilities. ... [2] has cooler visuals :) 

[1]https://en.wikipedia.org/wiki/Ripsaw_(vehicle)
[2] https://www.youtube.com/watch?v=P5FjZUwe000

> * What kinds of words would you use to describe Ripsaw that you would want to convey the spirit of in this logo (ie. innovative, cutting edge, fast, reliable, customizable, etc.)?

Fast, possibly destructive, and automated 

> * What types of places do you plan for this logo to be most prominent (Web, digital products/consoles, physical swag, printed materials, etc.)

Logo for github and stickers to be produced.

> 
> Looking forward to helping you out with this :)

Thank you!!

**Comment by maryshak1996** [comment]
@jtaleric that's great feedback! I'll take that info, run with some ideas, and post back here with some options soon!

**Comment by maryshak1996** [comment]
I did some initial work (I'll move onto colors and fine tuning once I know if I'm going down the right direction). I think that having a horizontal and vertical version of the logo would be good because you'd have the flexibility to use either one, depending on the context of the space that it's in
![Screen Shot 2019-04-08 at 4 23 58 PM](https://user-images.githubusercontent.com/19824574/55754721-5220aa00-5a1b-11e9-8204-b29e3b1fe5b6.png)

**Comment by maryshak1996** [comment]
^ @jtaleric

**Comment by aakarshg** [comment]
This is excellent work @maryshak1996 , this is kind of what I had in my mind as well. Thanks :-)

**Comment by jtaleric** [comment]
@maryshak1996 These are great! I love the graphic and the font!

**Comment by maryshak1996** [comment]
@aakarshg @jtaleric wooo! I'm glad that you like it :) is there anyone else that I should wait for it weigh in before moving on to some colors and refining?

**Comment by jtaleric** [comment]
@maryshak1996 Nothing from me, good to go!!

**Comment by dustinblack** [comment]
I dig it. Let's go!

**Comment by maryshak1996** [comment]
Comin to you live with an initial color exploration!
Any thoughts??
![Screen Shot 2019-04-12 at 4 02 34 PM](https://user-images.githubusercontent.com/19824574/56063161-80b0c480-5d3c-11e9-827f-ee6fe51c0d25.png)

**Comment by aakarshg** [comment]
@maryshak1996 this loooks good, and goes well with the theme of metalkube too. I like it,

**Comment by jtaleric** [comment]
Another +1 here! this is outstanding!

**Comment by dustinblack** [comment]
I think the colors are really cool! The only thing I'm not sure about is coloring only saw in ripsaw. It makes me read it with an accent on the second syllable.

**Comment by maryshak1996** [comment]
@dustinblack I think that that's fair! do you think that this works better?
![Screen Shot 2019-04-18 at 5 06 13 PM](https://user-images.githubusercontent.com/19824574/56391307-4a6fbb00-61fc-11e9-9591-f5b839eae77e.png)

**Comment by maryshak1996** [comment]
it's important that the text be accessible on both dark and light backgrounds, and the teal color will be more visible on both than the grey will be.

**Comment by maryshak1996** [comment]
Here are the full-color assets for the logo as shown above (SVG and hi-res PNG) as well as the all-white and all-black versions. Let me know if you need any other assets!
[RipSaw-LogoAssets.zip](https://github.com/cloud-bulldozer/ripsaw/files/3096199/RipSaw-LogoAssets.zip)

**Comment by jtaleric** [comment]
This is awesome work @maryshak1996 !! Thank you so much!
