### ISSUE TITLE
Simplify repo structure and installation process

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#84]
I still feel like we have some structural issues that make ripsaw harder to consume than it should be. Exactly what the best practices are to define and structure operator resources seems to be up for debate, but I would recommend we do something similar to rook.io where the operator and all of its k8s resource dependencies are deployed via 2 yaml files -- common.yaml (which houses the namespace definition, CRD, and all RBAC) and operator.yaml. I might even suggest that we simply converge _all_ of this into one operator.yaml file.

I think it is also a bit confusing the way the CR files are named and placed in the structure. I would suggest creating an `examples/` directory at the repo root and simplifying the naming convention of the files to just <workload_name>.yaml, <infra_name>.yaml, and <workload_name>-<infra_name>.yaml, as appropriate.

**Comment by bengland2** [comment]
I like the idea of separating the site-specific parts into a separate yaml file, so as much as possible is reusable.   In common yaml there should be a comment at the top saying "no user-serviceable parts inside" whereas the per-site.yaml should be heavily commented and have default values in it so people know when and where it's necessary to edit.

**Comment by dustinblack** [comment]
Thinking more about, this, I wouldn't converge all of the resources into a single file; I would keep the operator itself as its own definition. I often need to delete and re-deploy the operator, but I don't need at that time to delete and re-create all of the RBAC and related stuff, and in particular it can be troublesome to unnecessarily delete the namespace.

So I would propose converging every deployment-related item except the operator itself into one file, perhaps `common.yaml` like rook uses, so getting things going would simply look like:

```
$ kubectl apply -f deploy/common.yaml
$ kubectl apply -f deploy/operator.yaml
```

And then you could use default workload and/or infra CRs via an examples directory like below, or otherwise create your own custom CR files based on the examples:

```
$ kubectl apply -f examples/infra/couchbase.yaml
$ kubectl apply -f examples/workload/ycsb.yaml
```

I think it is important to put the CR files in a directory named _examples_ so that it is clear that these files may not be ready to use out-of-the-box.

**Comment by bengland2** [comment]
+1.   We could factor out the stuff that never changes into a single file,  to minimize the amount of yaml that people have to touch, and heavily comment the things that people do have to touch so they know what parts to change and what parts not to change.  

Is there a way to separate out all the must-change parts into a separate YAML file and make a yaml template file that these vars get injected into?  This is the UI model that the cluster-loader.py seems to have chosen.  For example, [smallfile-parameters.yaml](https://github.com/ekuric/svt/blob/smallfile_template/openshift_scalability/content/smallfile/smallfile-parameters.yaml) + [smallfile-template.json](https://github.com/ekuric/svt/blob/smallfile_template/openshift_scalability/content/smallfile/smallfile-template.json) or [fio-parameters.yaml](https://github.com/openshift/svt/blob/master/openshift_scalability/content/fio/fio-parameters.yaml) + [fio-template.json](https://github.com/openshift/svt/blob/master/openshift_scalability/content/fio/fio-template.json)

**Comment by dustinblack** [comment]
Here are my general recommendations for restructure. Please provide feedback.

1. Consolidate the scripts in the `deploy` directory. The 10..60 scripts should be merged into a single file, perhaps `common.yaml` to follow the rook.io example. There is basically zero reason you would ever deploy just one of these files, so this merge makes sense to simplify the installation process for the user.

2. Prepend the `resources/namespace.yaml` content to the same `common.yaml` file. No need to define this separately.

3. Move the `resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml` content to the same `common.yaml` as above. Again, the CRD is a standard part of the installation stack that is unlikely to require a separate `kubectl apply`, so let's simplify the user adoption by making this part of the one-file setup.

4. Move the `resources/operator.yaml` file to `deploy/operator.yaml` to consolidate the deployment-related files. Full deployment will then simply be `kubectl apply -f deploy/common.yaml && kubectl apply -f deploy/operator.yaml` or even just `kubectl apply -f deploy`. I still like keeping the `operator.yaml` separate from `common.yaml` because there are conditions under which we need to redeploy the operator pod but don't need to re-define all the dependency resources (CI is a good example of this).

5.  Move all of the CR files from `resources/crd/` to `examples/` and rename them to simplify. We could possibly even separate these into `examples/workloads/` and `examples/infra/` if it helps. The file renames should be very simple -- `ripsaw_v1alpha1_uperf_cr.yaml` should simply become `uperf.yaml`. These files should be heavily commented. I think this restructure and simplification is important to first of all make it blatantly obvious to a new user where to go in the repo to get started with workloads/infras and second to make it clear that these are _examples_ that may require tweaking for your $usecase.


So in the end, we would have a structure something like this:
```
.
├── deploy
│   ├── common.yaml
│   └── operator.yaml
└── examples
    ├── infra
    │   ├── couchbase.yaml
    │   ├── kafka.yaml
    │   ├── mariadb.yaml
    │   ├── mongodb.yaml
    │   ├── mssql.yaml
    │   └── postgresql.yaml
    └── workload
        ├── byowl.yaml
        ├── dvdstore3.yaml
        ├── fio-simple.yaml
        ├── fio-distributed.yaml
        ├── hammerdb.yaml
        ├── iperf3.yaml
        ├── smallfile.yaml
        ├── sysbench.yaml
        ├── uperf.yaml
        └── ycsb.yaml
```

**Comment by aakarshg** [comment]
> Here are my general recommendations for restructure. Please provide feedback.
> 
> 1. Consolidate the scripts in the `deploy` directory. The 10..60 scripts should be merged into a single file, perhaps `common.yaml` to follow the rook.io example. There is basically zero reason you would ever deploy just one of these files, so this merge makes sense to simplify the installation process for the user.

I think this makes sense.

> 2. Prepend the `resources/namespace.yaml` content to the same `common.yaml` file. No need to define this separately.

This isn't suggested, the namespace should be its own file. As sometimes, people would want to update the operator without having to delete the namespace. Even our CI doesn't delete the namespace. 

> 3. Move the `resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml` content to the same `common.yaml` as above. Again, the CRD is a standard part of the installation stack that is unlikely to require a separate `kubectl apply`, so let's simplify the user adoption by making this part of the one-file setup.
I'd agree with this change.
> 4. Move the `resources/operator.yaml` file to `deploy/operator.yaml` to consolidate the deployment-related files. Full deployment will then simply be `kubectl apply -f deploy/common.yaml && kubectl apply -f deploy/operator.yaml` or even just `kubectl apply -f deploy`. I still like keeping the `operator.yaml` separate from `common.yaml` because there are conditions under which we need to redeploy the operator pod but don't need to re-define all the dependency resources (CI is a good example of this).

I agree with this.

> 5. Move all of the CR files from `resources/crd/` to `examples/` and rename them to simplify. We could possibly even separate these into `examples/workloads/` and `examples/infra/` if it helps. The file renames should be very simple -- `ripsaw_v1alpha1_uperf_cr.yaml` should simply become `uperf.yaml`. These files should be heavily commented. I think this restructure and simplification is important to first of all make it blatantly obvious to a new user where to go in the repo to get started with workloads/infras and second to make it clear that these are _examples_ that may require tweaking for your $usecase.

This makes sense as well. 

> 
> So in the end, we would have a structure something like this:
> 
> ```
> .
> ├── deploy
> │   ├── common.yaml
> │   └── operator.yaml
> └── examples
>     ├── infra
>     │   ├── couchbase.yaml
>     │   ├── kafka.yaml
>     │   ├── mariadb.yaml
>     │   ├── mongodb.yaml
>     │   ├── mssql.yaml
>     │   └── postgresql.yaml
>     └── workload
>         ├── byowl.yaml
>         ├── dvdstore3.yaml
>         ├── fio-simple.yaml
>         ├── fio-distributed.yaml
>         ├── hammerdb.yaml
>         ├── iperf3.yaml
>         ├── smallfile.yaml
>         ├── sysbench.yaml
>         ├── uperf.yaml
>         └── ycsb.yaml
> ```

**Comment by dustinblack** [comment]
> This isn't suggested, the namespace should be its own file. As sometimes, people would want to update the operator without having to delete the namespace. Even our CI doesn't delete the namespace.

**Comment by dustinblack** [comment]
> > 1. Prepend the `resources/namespace.yaml` content to the same `common.yaml` file. No need to define this separately.
> 
> This isn't suggested, the namespace should be its own file. As sometimes, people would want to update the operator without having to delete the namespace. Even our CI doesn't delete the namespace.

This would be in the `common.yaml` (or `prereqs.yaml` or whatever it makes sense to call it) not in the `operator.yaml`, so the namespace would only get created/destroyed with the prerequisite $stuff not with the operator pod.

The rook.io `common.yaml` file takes this approach:

https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml

As does kubevirt.io (they actually bundle all prereqs _and_ the operator together):

https://github.com/kubevirt/kubevirt/blob/master/manifests/release/kubevirt-operator.yaml.in

As do things on operatorhub.io:

https://operatorhub.io/install/couchbase-operator.yaml
https://operatorhub.io/install/etcdoperator.yaml
https://operatorhub.io/install/prometheusoperator.yaml


Granted I could reference several operators that use different approaches, so ¯\_(ツ)_/¯

**Comment by dustinblack** [comment]
Based on bluejeans discussion, we'll leave the namespace out of the `common.yaml` file for now because it has a life/context outside of ripsaw for post-processing and because we have seen problems with other operators when deleting the prerequisite resources that deleting the namespace first (because it is at the top of the file) can cause it to hang in a perpetual terminating state.

**Comment by aakarshg** [comment]
Closing this issue as Ripsaw can now be installed through operatorhub, which is a single command install - `kubectl create -f https://operatorhub.io/install/ripsaw.yaml`

**Comment by dustinblack** [comment]
Re-opening. The operatorhub integration can simplify some installs, but the repo structure should still be changed, IMO.

**Comment by aakarshg** [comment]
do we want to keep this open @dustinblack ? thoughts @jtaleric @dry923 , the structure is the one created through operator-sdk so i'd recommend we leave it as is, helps with using operator-sdk features to generate csv as well.

**Comment by bengland2** [comment]
my thought is that Snafu is somewhat related to this.   All my changes of late have been to snafu and not ripsaw.   And all the CRs I need are consumed primarily by snafu and ripsaw pretty much just passes them through.   As far as ripsaw deployment, it is a 2-step process defined by running [this script ](http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/public/openshift/ripsaw/oc-install.sh
) first:


```
oc apply -f resources/namespace.yaml
oc project my-ripsaw
oc apply -f deploy/
oc apply -f resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
oc apply -f resources/operator.yaml
```

At that point I apply the CR for my specific benchmark and I'm done.   This two-step deploy process seems pretty ubiquitous, in RHOCS ocs-operator for example, because the operator has to be deployed before the CR can be even understood and parsed.   

comments @dustinblack @jtaleric @dry923 ?
