### ISSUE TITLE
uperf workload should default to testing between nodes

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#86]
Right now, unless you explicitly pin the clients and servers, uperf may (and often does) schedule the client and server component pods onto the same host. This leads to network testing only of the loopback of the host, which I do not think is generally useful.

I believe we should implement anti-affinity for the associated client and server pods so that by default they run on different nodes and therefore test real network connections.

**Comment by dry923** [comment]
This should be a relatively simple change adding the preferred affinity to be on a different node. I believe it should be something like this: [https://github.com/dry923/ripsaw/blob/3372a86ad5072b5687825082c1a0551e70f48aab/roles/uperf-bench/templates/workload.yml.j2#L48-L57](https://github.com/dry923/ripsaw/blob/3372a86ad5072b5687825082c1a0551e70f48aab/roles/uperf-bench/templates/workload.yml.j2#L48-L57 ) however I have not had the chance to test it on a multi-node cluster yet. It does still run the uperf test on my single minikube though with no noticeable errors.

**Comment by aakarshg** [comment]
This has been implemented with #238 i believe, @jtaleric can we close this ?
