### ISSUE TITLE
Allow for customizing CI tests based on environment and version

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#88]
This is particularly important for infra roles. It may not be possible to create one test CR for a role that could be expected to pass on all of K8s upstream, OCP 3.0, and OCP 4.0. If the CI system is going to automate testing of multiple environment types, then we need the ability to create test CRs that are applicable to the specifics of the environment.

**Comment by dustinblack** [comment]
Adding clarity as discussed on our call..

This mostly affects infra roles, as often you cannot use the exact same methods/tools/sources to install the infra on k8s, OCP 3, and OCP4. This means that I cannot easily create a single test CR file that will pass on all CI systems. What I propose is to add logic to the CI script structure that allows for varying the test scripts and/or the CR files based on the configuration of the test system.

**Comment by aakarshg** [comment]
This can be done today easily as Jenkins makes a list of variables available to the tests as environment variables [1]. We can then access them and manipulate in the test scripts as needed. For an example, we can look at PR #94 which was doing something similar with the variable NODE_NAME. So in this case, we can use the variable JOB_NAME, as JOB_NAME contains either minikube or minishift which will help us understand the environment. I'll add this to documentation with the job_name description.

[1] http://porthos.perf.lab.eng.rdu2.redhat.com:8080/env-vars.html/
[2] https://github.com/cloud-bulldozer/ripsaw/pull/94/files

**Comment by aakarshg** [comment]
Closing this now, as this can be accomplished through the above mentioned manner.
