### ISSUE TITLE
Do we need a Security Context Constraints for benchmark-operator/ripsaw ?

### ISSUE THREAD

**Issue by chawlanikhil24** [cloud-bulldozer/ripsaw#91]
While I was working on small-file operator,  I faced a lot of issues due to non-root privileges container, so , the solution we could rule out was to create an SCC and associated SA , then allowing the pods to run as root. But the difference was, I was not using a PVC to develop the smallfile operator. I don't think that when we will be working with PVC mounted on a mountpath, we could really see that issue. Hence,  I am creating this issue to have discussion and reach to a majority based opinion.

**Comment by aakarshg** [comment]
Closing this issue, given that smallfile was implemented in Ripsaw without the need for privileges to launch privileged pods. The workaround/issue was the mount path being set to `/tmp`.
